title: SANGEETH DAS KALLULLATHIL 
logo: "mypic.png?raw=true" 
description: > # your text below (remove <br> elements if you don't need line breaks)
  Ph.D. in Computational Chemistry, Queen's University
  <br><br>
  My background in mathematics and programming, acquired through my research work, has driven my transition into the data science industry.
  <br><br>
  <a href="https://www.linkedin.com/in/sangeeth-das-kallullathil/">View My LinkedIn Profile</a> 
  

google_analytics:
theme: jekyll-theme-minimal
