title: SANGEETH DAS KALLULLATHIL 
logo: "mypic.png?raw=true" 
description: > # your text below (remove <br> elements if you don't need line breaks)
  Ph.D. | Cyber Security | Cloud Security
  <br><br>
  I recently obtained PhD in Computational Chemistry and now transitioning into the Cybersecurity Industry.
  <br><br>
  <a href="https://www.linkedin.com/in/sangeeth-das-kallullathil/"> LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
