title: SANGEETH DAS KALLULLATHIL # your name (or website title) here
logo: "mypic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Ph.D. in Computational Chemistry, Queen's University, Canada
  <br><br>
  I hold a Ph.D. in Computational Chemistry from Queen's University, graduated in December 2022. With 7 years of extensive research experience in the field, I have developed expertise in software development for nuclear motion analysis in molecules. My strong background in mathematics and programming, acquired through my research work, has driven my transition into the data science industry. I am eager to bring my diverse skill set and continue to learn and grow as a data analyst, embracing new challenges along the way. 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
