title: SANGEETH DAS KALLULLATHIL # your name (or website title) here
logo: "mypic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Ph.D. in Computational Chemistry, Queen's University
  <br><br>
  My background in mathematics and programming, acquired through my research work, has driven my transition into the data science industry.
  <br><br>
  <a href="https://www.linkedin.com/in/sangeeth-das-kallullathil/">View My LinkedIn Profile</a> 
  
#theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
